import { ChevronRightIcon } from '@heroicons/react/solid'
import type { NextPage } from 'next'
import Head from 'next/head'
import Link from 'next/link'
import { Footer } from '../components/footer'
import { Header } from '../components/header'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <main className='text-white font-medium'>
        <section className='min-h-screen flex flex-col p-4 space-y-4 justify-center'>
          <h1 className='text-4xl before:content-["----"]'>Hi, I am Juan 👋</h1>
          <h2 className='text-2xl text-slate-400'>I break things while built others, along the way learn.</h2>
          <div className='grid grid-cols-2 h-12 w-full gap-4'>
            <Link href={"/projects"}><button className='primary-btn'>Go to Projects <ChevronRightIcon className='h-8' /></button></Link>
            <Link href={"/projects"}><button className='secondary-btn'>View blogs</button></Link>
          </div>
        </section>
      </main>
      <Footer/>
    </div>
  )
}

export default Home
